CREATE TABLE shop_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    status VARCHAR(24) NOT NULL CHECK (status IN ('PAYMENT_PENDING', 'PAID', 'EXPIRED', 'FAILED')),
    payment_method VARCHAR(32) NOT NULL CHECK (payment_method IN ('PROMPTPAY')),
    currency VARCHAR(3) NOT NULL CHECK (currency = 'THB'),
    total_minor BIGINT NOT NULL CHECK (total_minor > 0),
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX shop_orders_user_idempotency_key_uq
    ON shop_orders (user_id, idempotency_key);

CREATE INDEX shop_orders_user_status_idx
    ON shop_orders (user_id, status, created_at DESC);

CREATE TABLE shop_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_slug VARCHAR(120) NOT NULL,
    name_th VARCHAR(180) NOT NULL,
    name_en VARCHAR(180) NOT NULL,
    unit_price_minor INTEGER NOT NULL CHECK (unit_price_minor >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0 AND quantity <= 99)
);

CREATE INDEX shop_order_items_order_idx
    ON shop_order_items (order_id);

CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES shop_orders(id) ON DELETE CASCADE,
    provider VARCHAR(32) NOT NULL CHECK (provider = 'INWCLOUD'),
    transaction_id VARCHAR(120) UNIQUE,
    status VARCHAR(24) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'EXPIRED', 'FAILED')),
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    qr_url TEXT,
    payload TEXT,
    expires_at TIMESTAMPTZ,
    checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX payment_transactions_status_expiry_idx
    ON payment_transactions (status, expires_at);

CREATE FUNCTION reserve_product_stock(p_product_id BIGINT, p_quantity INTEGER)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
    IF p_quantity <= 0 THEN
        RETURN FALSE;
    END IF;

    UPDATE products
    SET stock_quantity = stock_quantity - p_quantity
    WHERE id = p_product_id
      AND active = TRUE
      AND stock_quantity >= p_quantity;
    RETURN FOUND;
END
$function$;

CREATE FUNCTION release_product_stock(p_product_id BIGINT, p_quantity INTEGER)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
    IF p_quantity <= 0 THEN
        RETURN FALSE;
    END IF;

    UPDATE products
    SET stock_quantity = stock_quantity + p_quantity
    WHERE id = p_product_id;
    RETURN FOUND;
END
$function$;

REVOKE ALL ON FUNCTION reserve_product_stock(BIGINT, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION release_product_stock(BIGINT, INTEGER) FROM PUBLIC;
