COMMENT ON TABLE products IS 'แคตตาล็อกสินค้าดิจิทัลที่เผยแพร่บนหน้าร้าน';
COMMENT ON COLUMN products.id IS 'รหัสสินค้าภายในระบบ';
COMMENT ON COLUMN products.slug IS 'ตัวระบุสินค้าแบบอ่านง่ายสำหรับ URL และการอ้างอิง';
COMMENT ON COLUMN products.name_th IS 'ชื่อสินค้า ภาษาไทย';
COMMENT ON COLUMN products.name_en IS 'ชื่อสินค้า ภาษาอังกฤษ';
COMMENT ON COLUMN products.description_th IS 'รายละเอียดสินค้า ภาษาไทย';
COMMENT ON COLUMN products.description_en IS 'รายละเอียดสินค้า ภาษาอังกฤษ';
COMMENT ON COLUMN products.visual_code IS 'รหัสภาพหรือรหัส visual ที่ใช้แสดงผลสินค้า';
COMMENT ON COLUMN products.type IS 'ประเภทสินค้า: SINGLE หรือ BUNDLE';
COMMENT ON COLUMN products.price_minor IS 'ราคาสินค้าในหน่วย satang โดย 100 satang เท่ากับ 1 THB';
COMMENT ON COLUMN products.currency IS 'สกุลเงินของราคา ปัจจุบันต้องเป็น THB';
COMMENT ON COLUMN products.stock_quantity IS 'จำนวนสินค้าคงเหลือที่พร้อมจำหน่าย';
COMMENT ON COLUMN products.bundle_item_count IS 'จำนวนรายการภายใน bundle; เป็น NULL สำหรับสินค้าเดี่ยว';
COMMENT ON COLUMN products.instant_delivery IS 'ระบุว่าสินค้าดิจิทัลส่งมอบได้ทันทีหรือไม่';
COMMENT ON COLUMN products.catalog_order IS 'ลำดับการแสดงสินค้าใน catalog';
COMMENT ON COLUMN products.active IS 'สถานะการเผยแพร่สินค้า; false หมายถึงถูก archive';
COMMENT ON COLUMN products.updated_at IS 'เวลาที่ข้อมูลสินค้าถูกแก้ไขล่าสุด';
COMMENT ON COLUMN products.updated_by IS 'OIDC subject ของ admin ที่แก้ไขสินค้าล่าสุด';
COMMENT ON COLUMN products.version IS 'เลข version สำหรับ optimistic locking ของ admin mutation';
COMMENT ON COLUMN products.selection_mode IS 'โหมดเลือกสินค้า: SINGLE_OPTION หรือ MULTI_OPTION';
COMMENT ON COLUMN products.option_group IS 'ตัวระบุกลุ่มตัวเลือกที่ใช้รวมหลายรายการเป็นสินค้ากลุ่มเดียวบนหน้าร้าน';
COMMENT ON COLUMN products.option_label_th IS 'ชื่อ option ภาษาไทย';
COMMENT ON COLUMN products.option_label_en IS 'ชื่อ option ภาษาอังกฤษ';

COMMENT ON TABLE app_users IS 'ข้อมูล identity ของผู้ใช้ที่ผูกกับ OIDC issuer และ subject';
COMMENT ON COLUMN app_users.id IS 'รหัสผู้ใช้ภายในระบบ';
COMMENT ON COLUMN app_users.issuer IS 'URL ของ OIDC identity provider ที่ออก identity นี้';
COMMENT ON COLUMN app_users.subject IS 'ค่า OIDC sub ที่ระบุผู้ใช้ภายใน issuer';
COMMENT ON COLUMN app_users.email IS 'อีเมลของผู้ใช้จาก identity provider';
COMMENT ON COLUMN app_users.display_name IS 'ชื่อที่แสดงของผู้ใช้จาก identity provider';
COMMENT ON COLUMN app_users.status IS 'สถานะบัญชี: ACTIVE หรือ DISABLED';
COMMENT ON COLUMN app_users.created_at IS 'เวลาที่สร้างข้อมูลผู้ใช้';
COMMENT ON COLUMN app_users.updated_at IS 'เวลาที่อัปเดตข้อมูลผู้ใช้ล่าสุด';

COMMENT ON TABLE carts IS 'รถเข็นที่เป็นของบัญชีผู้ใช้; guest cart อยู่ใน browser ก่อน merge';
COMMENT ON COLUMN carts.id IS 'รหัสรถเข็นภายในระบบ';
COMMENT ON COLUMN carts.user_id IS 'รหัสเจ้าของรถเข็น อ้างอิง app_users.id';
COMMENT ON COLUMN carts.status IS 'สถานะรถเข็น: ACTIVE, MERGED หรือ ABANDONED';
COMMENT ON COLUMN carts.version IS 'เลข version สำหรับตรวจ optimistic locking ของรถเข็น';
COMMENT ON COLUMN carts.created_at IS 'เวลาที่สร้างรถเข็น';
COMMENT ON COLUMN carts.updated_at IS 'เวลาที่อัปเดตรถเข็นล่าสุด';

COMMENT ON TABLE cart_items IS 'รายการสินค้าและจำนวนที่อยู่ในรถเข็น';
COMMENT ON COLUMN cart_items.id IS 'รหัสรายการในรถเข็น';
COMMENT ON COLUMN cart_items.cart_id IS 'รหัสรถเข็น อ้างอิง carts.id';
COMMENT ON COLUMN cart_items.product_id IS 'รหัสสินค้า อ้างอิง products.id';
COMMENT ON COLUMN cart_items.quantity IS 'จำนวนสินค้าที่เลือกในรถเข็น';
COMMENT ON COLUMN cart_items.created_at IS 'เวลาที่เพิ่มรายการเข้ารถเข็น';
COMMENT ON COLUMN cart_items.updated_at IS 'เวลาที่แก้ไขรายการในรถเข็นล่าสุด';

COMMENT ON TABLE product_audit_log IS 'ประวัติการเปลี่ยนแปลงสินค้าโดยผู้มีสิทธิ์ admin';
COMMENT ON COLUMN product_audit_log.id IS 'รหัสรายการ audit';
COMMENT ON COLUMN product_audit_log.product_id IS 'รหัสสินค้าที่ถูกเปลี่ยนแปลง อ้างอิง products.id';
COMMENT ON COLUMN product_audit_log.action IS 'ประเภทการเปลี่ยนแปลง: CREATE, UPDATE, STOCK หรือ ARCHIVE';
COMMENT ON COLUMN product_audit_log.actor_issuer IS 'OIDC issuer ของผู้ทำรายการ';
COMMENT ON COLUMN product_audit_log.actor_subject IS 'OIDC subject ของผู้ทำรายการ';
COMMENT ON COLUMN product_audit_log.changed_fields IS 'รายละเอียด field ที่เปลี่ยนแปลงในรูปแบบ JSONB';
COMMENT ON COLUMN product_audit_log.created_at IS 'เวลาที่บันทึก audit';

COMMENT ON TABLE shop_orders IS 'คำสั่งซื้อสินค้าของผู้ใช้และสถานะการชำระเงิน';
COMMENT ON COLUMN shop_orders.id IS 'รหัสคำสั่งซื้อ';
COMMENT ON COLUMN shop_orders.user_id IS 'รหัสผู้สั่งซื้อ อ้างอิง app_users.id';
COMMENT ON COLUMN shop_orders.status IS 'สถานะคำสั่งซื้อ: PAYMENT_PENDING, PAID, EXPIRED, FAILED หรือ PAYMENT_REVIEW';
COMMENT ON COLUMN shop_orders.payment_method IS 'ช่องทางชำระเงิน: PROMPTPAY หรือ TRUEWALLET';
COMMENT ON COLUMN shop_orders.currency IS 'สกุลเงินของคำสั่งซื้อ ปัจจุบันต้องเป็น THB';
COMMENT ON COLUMN shop_orders.total_minor IS 'ยอดรวมคำสั่งซื้อในหน่วย satang โดย 100 satang เท่ากับ 1 THB';
COMMENT ON COLUMN shop_orders.idempotency_key IS 'คีย์ป้องกันการสร้างคำสั่งซื้อซ้ำจากคำขอเดิม';
COMMENT ON COLUMN shop_orders.created_at IS 'เวลาที่สร้างคำสั่งซื้อ';
COMMENT ON COLUMN shop_orders.updated_at IS 'เวลาที่อัปเดตคำสั่งซื้อล่าสุด';
COMMENT ON COLUMN shop_orders.paid_at IS 'เวลาที่คำสั่งซื้อถูกยืนยันว่าชำระเงินสำเร็จ';

COMMENT ON TABLE shop_order_items IS 'รายการสินค้าในคำสั่งซื้อพร้อมข้อมูล snapshot ณ เวลาสั่งซื้อ';
COMMENT ON COLUMN shop_order_items.id IS 'รหัสรายการสินค้าในคำสั่งซื้อ';
COMMENT ON COLUMN shop_order_items.order_id IS 'รหัสคำสั่งซื้อ อ้างอิง shop_orders.id';
COMMENT ON COLUMN shop_order_items.product_id IS 'รหัสสินค้าเดิม อ้างอิง products.id';
COMMENT ON COLUMN shop_order_items.product_slug IS 'ค่า slug ของสินค้าที่ snapshot ไว้ ณ เวลาสั่งซื้อ';
COMMENT ON COLUMN shop_order_items.name_th IS 'ชื่อสินค้าภาษาไทยที่ snapshot ไว้ ณ เวลาสั่งซื้อ';
COMMENT ON COLUMN shop_order_items.name_en IS 'ชื่อสินค้าภาษาอังกฤษที่ snapshot ไว้ ณ เวลาสั่งซื้อ';
COMMENT ON COLUMN shop_order_items.unit_price_minor IS 'ราคาต่อหน่วยที่ snapshot ไว้ในหน่วย satang';
COMMENT ON COLUMN shop_order_items.quantity IS 'จำนวนสินค้าที่สั่งซื้อในรายการนี้';

COMMENT ON TABLE payment_transactions IS 'รายการธุรกรรมที่ส่งไปตรวจสอบกับ payment provider';
COMMENT ON COLUMN payment_transactions.id IS 'รหัสธุรกรรมภายในระบบ';
COMMENT ON COLUMN payment_transactions.order_id IS 'รหัสคำสั่งซื้อ อ้างอิง shop_orders.id';
COMMENT ON COLUMN payment_transactions.provider IS 'ชื่อ payment provider ที่ใช้ทำรายการ';
COMMENT ON COLUMN payment_transactions.transaction_id IS 'รหัสธุรกรรมที่ provider ส่งกลับมา';
COMMENT ON COLUMN payment_transactions.status IS 'สถานะธุรกรรม: PENDING, PAID, EXPIRED, FAILED หรือ REVIEW';
COMMENT ON COLUMN payment_transactions.amount_minor IS 'ยอดที่ระบบส่งให้ provider ในหน่วย satang';
COMMENT ON COLUMN payment_transactions.qr_url IS 'URL ของ QR code สำหรับชำระเงิน ถ้ามี';
COMMENT ON COLUMN payment_transactions.payload IS 'payload ที่ใช้สร้างหรือส่งให้ provider ถ้ามี';
COMMENT ON COLUMN payment_transactions.expires_at IS 'เวลาหมดอายุของธุรกรรมหรือ QR code';
COMMENT ON COLUMN payment_transactions.checked_at IS 'เวลาที่ระบบตรวจสอบสถานะกับ provider ล่าสุด';
COMMENT ON COLUMN payment_transactions.created_at IS 'เวลาที่สร้างธุรกรรม';
COMMENT ON COLUMN payment_transactions.updated_at IS 'เวลาที่อัปเดตธุรกรรมล่าสุด';
COMMENT ON COLUMN payment_transactions.provider_amount_minor IS 'ยอดเงินที่ provider รายงานกลับมาในหน่วย satang';

COMMENT ON TABLE flyway_schema_history IS 'ตาราง metadata ที่ Flyway ใช้ติดตาม migration';
COMMENT ON COLUMN flyway_schema_history.installed_rank IS 'ลำดับที่ migration ถูกติดตั้ง';
COMMENT ON COLUMN flyway_schema_history.version IS 'หมายเลข version ของ migration';
COMMENT ON COLUMN flyway_schema_history.description IS 'คำอธิบาย migration';
COMMENT ON COLUMN flyway_schema_history.type IS 'ประเภทของ migration เช่น SQL';
COMMENT ON COLUMN flyway_schema_history.script IS 'ชื่อไฟล์ migration ที่ถูกติดตั้ง';
COMMENT ON COLUMN flyway_schema_history.checksum IS 'checksum ที่ใช้ตรวจว่าไฟล์ migration ไม่ถูกแก้หลังติดตั้ง';
COMMENT ON COLUMN flyway_schema_history.installed_by IS 'database role ที่ติดตั้ง migration';
COMMENT ON COLUMN flyway_schema_history.installed_on IS 'เวลาที่ติดตั้ง migration';
COMMENT ON COLUMN flyway_schema_history.execution_time IS 'เวลาที่ migration ใช้ในการทำงาน หน่วยมิลลิวินาที';
COMMENT ON COLUMN flyway_schema_history.success IS 'ระบุว่า migration ทำงานสำเร็จหรือไม่';
