CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    name_th VARCHAR(180) NOT NULL,
    name_en VARCHAR(180) NOT NULL,
    description_th VARCHAR(1000) NOT NULL,
    description_en VARCHAR(1000) NOT NULL,
    visual_code VARCHAR(80) NOT NULL UNIQUE,
    type VARCHAR(16) NOT NULL CHECK (type IN ('SINGLE', 'BUNDLE')),
    price_minor INTEGER NOT NULL CHECK (price_minor >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'THB' CHECK (currency = 'THB'),
    stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
    bundle_item_count INTEGER,
    instant_delivery BOOLEAN NOT NULL,
    catalog_order INTEGER NOT NULL UNIQUE CHECK (catalog_order > 0),
    CONSTRAINT products_bundle_item_count_check CHECK (
        (type = 'SINGLE' AND bundle_item_count IS NULL)
        OR (type = 'BUNDLE' AND bundle_item_count >= 2)
    )
);

COMMENT ON TABLE products IS 'Read-only public creative-asset product catalog';
COMMENT ON COLUMN products.price_minor IS 'Fixed THB price in satang; seed uses whole USD reference price * 35 * 100';
