CREATE TABLE product_fulfillment_profiles (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE RESTRICT,
    fulfillment_type VARCHAR(32) NOT NULL CHECK (
        fulfillment_type IN (
            'NONE',
            'DISCORD_ACCOUNT',
            'LICENSE_KEY',
            'INVITE_URL',
            'REDEEM_CODE',
            'MANUAL_INSTRUCTION'
        )
    ),
    provider VARCHAR(64),
    payload_schema_version SMALLINT NOT NULL DEFAULT 1 CHECK (payload_schema_version > 0),
    quantity_policy VARCHAR(32) NOT NULL DEFAULT 'ONE_PER_ORDER_LINE' CHECK (
        quantity_policy IN ('ONE_PER_ORDER_LINE')
    ),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT product_fulfillment_profiles_none_provider_check
        CHECK (fulfillment_type <> 'NONE' OR provider IS NULL),
    CONSTRAINT product_fulfillment_profiles_product_type_uq
        UNIQUE (product_id, fulfillment_type)
);

COMMENT ON TABLE product_fulfillment_profiles IS
    'รูปแบบการส่งมอบของสินค้าที่ซื้อได้จริง; ไม่เก็บ credential หรือ payload ลับ';
COMMENT ON COLUMN product_fulfillment_profiles.product_id IS
    'รหัส product หรือ multi-option child ที่เป็นเจ้าของรูปแบบการส่งมอบ';
COMMENT ON COLUMN product_fulfillment_profiles.fulfillment_type IS
    'ชนิด payload ที่ allowlist ไว้ เช่น DISCORD_ACCOUNT, LICENSE_KEY หรือ INVITE_URL';
COMMENT ON COLUMN product_fulfillment_profiles.provider IS
    'ผู้ให้บริการของ payload เช่น DISCORD; ห้ามใช้เก็บ credential';
COMMENT ON COLUMN product_fulfillment_profiles.payload_schema_version IS
    'เวอร์ชัน schema ที่ backend validator รองรับ';
COMMENT ON COLUMN product_fulfillment_profiles.quantity_policy IS
    'กฎจำนวนต่อรายการสั่งซื้อ; รุ่นแรกส่งมอบ secure item ได้หนึ่งชุดต่อ cart line';
COMMENT ON COLUMN product_fulfillment_profiles.version IS
    'เลข version สำหรับ optimistic locking ของ fulfillment profile';

CREATE TABLE product_fulfillment_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL CHECK (step_order > 0),
    audience VARCHAR(16) NOT NULL CHECK (audience IN ('CUSTOMER', 'OPERATOR')),
    title_th VARCHAR(180) NOT NULL,
    title_en VARCHAR(180) NOT NULL,
    body_th VARCHAR(4000) NOT NULL,
    body_en VARCHAR(4000) NOT NULL,
    link_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT product_fulfillment_steps_order_uq
        UNIQUE (product_id, audience, step_order),
    CONSTRAINT product_fulfillment_steps_link_check
        CHECK (link_url IS NULL OR length(link_url) <= 2048)
);

COMMENT ON TABLE product_fulfillment_steps IS
    'ขั้นตอนการส่งมอบที่ไม่ใช่ secret แยกตามผู้รับขั้นตอน CUSTOMER หรือ OPERATOR';
COMMENT ON COLUMN product_fulfillment_steps.product_id IS
    'รหัส product หรือ child ที่เป็นเจ้าของ template ขั้นตอน';
COMMENT ON COLUMN product_fulfillment_steps.step_order IS
    'ลำดับการแสดงขั้นตอนภายใน product และ audience เดียวกัน';
COMMENT ON COLUMN product_fulfillment_steps.audience IS
    'กลุ่มผู้เห็นขั้นตอน; OPERATOR ห้ามส่งออกใน customer response';
COMMENT ON COLUMN product_fulfillment_steps.body_th IS
    'รายละเอียดขั้นตอนภาษาไทยที่ไม่ควรมี credential หรือ access token';
COMMENT ON COLUMN product_fulfillment_steps.body_en IS
    'รายละเอียดขั้นตอนภาษาอังกฤษที่ไม่ควรมี credential หรือ access token';

DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_user') THEN
        EXECUTE 'GRANT SELECT ON TABLE product_fulfillment_profiles, product_fulfillment_steps TO pluto_user';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_admin') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON TABLE product_fulfillment_profiles TO pluto_admin';
        EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE product_fulfillment_steps TO pluto_admin';
        EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE product_fulfillment_steps_id_seq TO pluto_admin';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_inspector') THEN
        EXECUTE 'GRANT SELECT ON TABLE product_fulfillment_profiles, product_fulfillment_steps TO pluto_inspector';
    END IF;
END
$migration$;
