CREATE TABLE digital_inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    fulfillment_type VARCHAR(32) NOT NULL CONSTRAINT digital_inventory_items_type_check CHECK (
        fulfillment_type IN ('DISCORD_ACCOUNT', 'LICENSE_KEY', 'INVITE_URL', 'REDEEM_CODE')
    ),
    provider VARCHAR(64) NOT NULL,
    payload_schema_version SMALLINT NOT NULL CHECK (payload_schema_version > 0),
    secret_ciphertext BYTEA NOT NULL,
    secret_nonce BYTEA NOT NULL,
    encryption_key_version SMALLINT NOT NULL CHECK (encryption_key_version > 0),
    secret_fingerprint BYTEA NOT NULL,
    status VARCHAR(16) NOT NULL CONSTRAINT digital_inventory_items_status_check CHECK (
        status IN ('AVAILABLE', 'RESERVED', 'DELIVERED', 'REVOKED', 'QUARANTINED')
    ),
    public_metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    external_label VARCHAR(180),
    expires_at TIMESTAMPTZ,
    reserved_until TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT digital_inventory_items_product_type_fkey
        FOREIGN KEY (product_id, fulfillment_type)
        REFERENCES product_fulfillment_profiles(product_id, fulfillment_type)
        ON DELETE RESTRICT,
    CONSTRAINT digital_inventory_items_fingerprint_uq
        UNIQUE (product_id, fulfillment_type, provider, secret_fingerprint),
    CONSTRAINT digital_inventory_items_provider_not_blank
        CHECK (length(btrim(provider)) > 0),
    CONSTRAINT digital_inventory_items_public_metadata_object_check
        CHECK (jsonb_typeof(public_metadata_jsonb) = 'object'),
    CONSTRAINT digital_inventory_items_public_metadata_secret_check
        CHECK (NOT (public_metadata_jsonb ?| ARRAY[
            'email', 'password', 'licenseKey', 'license_key',
            'inviteUrl', 'invite_url', 'code', 'secret', 'token'
        ]))
);

COMMENT ON TABLE digital_inventory_items IS
    'คลัง secure item ต่อหนึ่งหน่วยสินค้า; secret payload ถูกเข้ารหัสก่อนเก็บและไม่เปิดให้ inspector อ่าน';
COMMENT ON COLUMN digital_inventory_items.product_id IS
    'รหัส product หรือ multi-option child ที่เป็นเจ้าของ secure item';
COMMENT ON COLUMN digital_inventory_items.fulfillment_type IS
    'ชนิด payload ของแถวนี้และต้องตรงกับ profile ของ product_id';
COMMENT ON COLUMN digital_inventory_items.payload_schema_version IS
    'เวอร์ชัน typed payload ที่ validator/handler รองรับ';
COMMENT ON COLUMN digital_inventory_items.secret_ciphertext IS
    'payload ลับที่เข้ารหัสแบบ authenticated encryption; ห้ามเก็บ plaintext';
COMMENT ON COLUMN digital_inventory_items.secret_nonce IS
    'nonce ที่สุ่มใหม่ต่อ record สำหรับถอดรหัส payload';
COMMENT ON COLUMN digital_inventory_items.encryption_key_version IS
    'เวอร์ชัน key ที่ใช้เข้ารหัส เพื่อรองรับ key rotation';
COMMENT ON COLUMN digital_inventory_items.secret_fingerprint IS
    'blind index จาก HMAC สำหรับตรวจข้อมูลซ้ำ โดยไม่สามารถย้อนกลับเป็น secret ได้';
COMMENT ON COLUMN digital_inventory_items.public_metadata_jsonb IS
    'metadata ที่อนุญาตให้แสดงแบบ masked เช่น provider, expiry หรือ region; ห้ามมี secret';
COMMENT ON COLUMN digital_inventory_items.status IS
    'สถานะคลัง: AVAILABLE, RESERVED, DELIVERED, REVOKED หรือ QUARANTINED';

CREATE INDEX digital_inventory_items_available_idx
    ON digital_inventory_items (product_id, id)
    WHERE status = 'AVAILABLE';

CREATE INDEX digital_inventory_items_status_idx
    ON digital_inventory_items (product_id, status, updated_at);

CREATE TABLE order_fulfillments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL UNIQUE REFERENCES shop_order_items(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    fulfillment_type VARCHAR(32) NOT NULL CHECK (
        fulfillment_type IN (
            'NONE', 'DISCORD_ACCOUNT', 'LICENSE_KEY', 'INVITE_URL',
            'REDEEM_CODE', 'MANUAL_INSTRUCTION'
        )
    ),
    delivery_type VARCHAR(16) NOT NULL CHECK (delivery_type IN ('INSTANT', 'MANUAL')),
    status VARCHAR(16) NOT NULL CHECK (
        status IN ('PENDING', 'RESERVED', 'READY', 'DELIVERED', 'FAILED', 'RELEASED', 'REVOKED')
    ),
    instructions_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    failure_code VARCHAR(64),
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    delivered_by VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT order_fulfillments_instructions_array_check
        CHECK (jsonb_typeof(instructions_snapshot) = 'array')
);

COMMENT ON TABLE order_fulfillments IS
    'สถานะการส่งมอบต่อ order item พร้อม snapshot ขั้นตอนที่ไม่ใช่ secret';
COMMENT ON COLUMN order_fulfillments.instructions_snapshot IS
    'ขั้นตอน CUSTOMER ที่ snapshot ไว้ ณ เวลาสร้าง fulfillment; ห้ามมี credential';
COMMENT ON COLUMN order_fulfillments.failure_code IS
    'รหัสข้อผิดพลาดแบบ sanitized สำหรับ retry/support; ห้ามเก็บ provider body หรือ secret';

CREATE INDEX order_fulfillments_status_idx
    ON order_fulfillments (status, updated_at);

CREATE TABLE order_fulfillment_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_fulfillment_id BIGINT NOT NULL REFERENCES order_fulfillments(id) ON DELETE CASCADE,
    inventory_item_id BIGINT NOT NULL REFERENCES digital_inventory_items(id) ON DELETE RESTRICT,
    unit_index INTEGER NOT NULL CHECK (unit_index > 0),
    status VARCHAR(16) NOT NULL CHECK (status IN ('RESERVED', 'DELIVERED', 'RELEASED', 'REVOKED')),
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT order_fulfillment_allocations_inventory_uq
        UNIQUE (inventory_item_id),
    CONSTRAINT order_fulfillment_allocations_order_unit_uq
        UNIQUE (order_fulfillment_id, unit_index)
);

COMMENT ON TABLE order_fulfillment_allocations IS
    'การจับคู่ secure inventory item กับ order fulfillment ต่อหนึ่งหน่วยสินค้า';
COMMENT ON COLUMN order_fulfillment_allocations.inventory_item_id IS
    'รหัส inventory ที่ถูกจอง; unique เพื่อป้องกันการส่ง credential ชุดเดียวกันซ้ำ';
COMMENT ON COLUMN order_fulfillment_allocations.unit_index IS
    'ลำดับหน่วยสินค้าใน order item; รุ่นแรกจำกัด quantity หนึ่ง';

CREATE INDEX order_fulfillment_allocations_fulfillment_idx
    ON order_fulfillment_allocations (order_fulfillment_id, status);

CREATE TABLE fulfillment_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    order_fulfillment_id BIGINT REFERENCES order_fulfillments(id) ON DELETE SET NULL,
    inventory_item_id BIGINT REFERENCES digital_inventory_items(id) ON DELETE SET NULL,
    action VARCHAR(16) NOT NULL CHECK (
        action IN ('CONFIGURE', 'IMPORT', 'RESERVE', 'RELEASE', 'ASSIGN', 'DELIVER', 'REVEAL', 'REVOKE', 'FAIL', 'QUARANTINE')
    ),
    actor_issuer VARCHAR(255),
    actor_subject VARCHAR(255),
    metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fulfillment_audit_metadata_object_check
        CHECK (jsonb_typeof(metadata_jsonb) = 'object'),
    CONSTRAINT fulfillment_audit_metadata_secret_check
        CHECK (NOT (metadata_jsonb ?| ARRAY[
            'email', 'password', 'licenseKey', 'license_key',
            'inviteUrl', 'invite_url', 'code', 'secret', 'token',
            'ciphertext', 'nonce'
        ]))
);

COMMENT ON TABLE fulfillment_audit_log IS
    'ประวัติการจอง/ส่งมอบ secure item โดยเก็บเฉพาะ actor, entity id และ metadata ที่ไม่ลับ';
COMMENT ON COLUMN fulfillment_audit_log.metadata_jsonb IS
    'รายละเอียดที่ผ่านการ sanitize แล้ว; ห้ามเก็บ request body, provider response หรือ credential';

CREATE INDEX fulfillment_audit_log_order_idx
    ON fulfillment_audit_log (order_fulfillment_id, created_at DESC);

DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_user') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON TABLE digital_inventory_items, order_fulfillments, order_fulfillment_allocations TO pluto_user';
        EXECUTE 'GRANT INSERT ON TABLE fulfillment_audit_log TO pluto_user';
        EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE order_fulfillments_id_seq, order_fulfillment_allocations_id_seq, fulfillment_audit_log_id_seq TO pluto_user';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_admin') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON TABLE digital_inventory_items TO pluto_admin';
        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON TABLE order_fulfillments, order_fulfillment_allocations TO pluto_admin';
        EXECUTE 'GRANT SELECT, INSERT ON TABLE fulfillment_audit_log TO pluto_admin';
        EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE digital_inventory_items_id_seq, order_fulfillments_id_seq, order_fulfillment_allocations_id_seq, fulfillment_audit_log_id_seq TO pluto_admin';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pluto_inspector') THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE digital_inventory_items FROM pluto_inspector';
        EXECUTE 'REVOKE ALL PRIVILEGES ON SEQUENCE digital_inventory_items_id_seq FROM pluto_inspector';
        EXECUTE 'GRANT SELECT ON TABLE order_fulfillments, order_fulfillment_allocations TO pluto_inspector';
    END IF;
END
$migration$;
