CREATE TABLE product_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    action VARCHAR(16) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'STOCK', 'ARCHIVE')),
    actor_issuer VARCHAR(500) NOT NULL,
    actor_subject VARCHAR(255) NOT NULL,
    changed_fields JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX product_audit_log_product_id_idx ON product_audit_log (product_id);
CREATE INDEX product_audit_log_created_at_idx ON product_audit_log (created_at DESC);

COMMENT ON TABLE product_audit_log IS 'Immutable audit trail for server-authorized product mutations';
